### ISSUE TITLE
[Epic] Migration to new Content API

### ISSUE THREAD

**Issue by Figments** [OffprintStudios/dragonfish#209]
Works and Blogs need to be migrated, alongside all relevant functionality. Navigating to existing works and blogs should automatically begin the process of transferring them to the content API.

To be done:

- [x] Blogs
  - [x] Can create new Blog
  - [x] Can update existing Blog
  - [x] Can unpublish Blog
  - [x] Can delete Blog
- [x] Prose
  - [x] Can create new Prose
  - [x] Can update existing Prose
  - [x] Can publish sections
  - [x] Can unpublish sections
  - [x] Can delete sections
  - [x] Can upload cover art
  - [x] Can add Prose to the approval queue
  - [x] Can publish Prose
  - [x] Can delete Prose
- [x] Poetry
  - [x] Can create new Poem
  - [x] Can update existing Poem
  - [x] Can delete Poem
  - [x] Can create new Poetry collection
  - [x] Can update existing Poetry collection
  - [x] Can delete Poetry Collection
  - [x] Can add section to Poetry collection
  - [x] Can delete section from Poetry collection
  - [x] Can publish Poetry collection section
  - [x] Can unpublish Poetry collection section
  - [x] Can publish Poem
  - [x] Can add Poetry to the approval queue
  - [x] Can publish Poetry collection
  - [x] Can upload cover art
- [x] Migration Tools
  - [x] Migration for Blogs
  - [x] Migration for Works
    - [x] Prose
    - [x] Poetry
- [x] Browse page
  - [x] Call out to the Content API instead of the old API (In progress: https://github.com/OffprintStudios/pulp-fiction/pull/235)
- [x] Search page
  - [x] Update search page to use the new Content API models
  - [x] Update the client-side `SearchService`s to talk to the Content API
  - [x] Update the `Blog`, `Prose` and `Poetry` Content services in the backend to return Search-related information

**Comment by Figments** [comment]
unpublishing prose and poetry will come in a future update since that one has special considerations to address, like "should republishing fics also require another trip through the approval queue?"

**Comment by Figments** [comment]
Search has now been merged
